# Generated by Django 5.2.8 on 2025-11-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectversion',
            name='description_snapshot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectversion',
            name='title_snapshot',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
